### ISSUE TITLE
R CMD check warning: Documenting an options function in a package

### ISSUE THREAD

**Issue by rcst** [jokergoo/GlobalOptions#4]
Hi,
thanks for this package, I think it's immensely practical.
I'm using it to handle options in my [package](https://github.com/rcst/rim) (R/options.R).

I've documented all my options using Roxygen2 like that
```
#' maxima.options
#'
#' Function for globally setting and retrieving options.
#'
#' To print a table of available options, current settings and a description simply print the function object (without parentheses), i.e. \code{maxima.options} or \code{print(maxima.options)}.
#'
#' @param format character vector of length 1 setting the output format for \code{maxima.get()}. Can be one of "linear", "ascii", "latex" or "mathml".
...
#' @export
maxima.options = set_opt(
  format = list(.value = "linear",
		.length = 1L,
		.class = "character", 
		.read.only = FALSE, 
		.validate = function(x) x %in% c("linear", "ascii", "latex", "mathml"),
		.failed_msg = "'format' must be one of 'linear', 'ascii', 'latex' or 'mathml'",
		.description = "Printing format of returned object from maxima.get()"),
...
```
However this causes a warning in `R CMD check` saying:
```
❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'maxima.options'
    ‘...’ ‘RESET’ ‘READ.ONLY’ ‘LOCAL’ ‘ADD’
  Documented arguments not in \usage in documentation object 'maxima.options':
    ‘format’ ‘engine.format’ ‘inline.format’ ‘label’ ‘engine.label’
    ‘inline.label’

  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

0 errors ✔ | 1 warning ✖ | 0 notes ✔
```
This warning will lead to a rejection from CRAN when I want to update my package. For one thing, the added options are not shown in a corresponding usage section. I don't know what to do about that. 

Second, I think it's not a real problem to just manually add the standard parameters to the documentation (maybe simply link it). But the first issue still prevails.

Would there be a way to handle this from your side? Or any hint or tip?

Thanks in advance!
Eric

**Comment by jokergoo** [comment]
You can add one line:

```r
maxima.options = function(..., RESET = FALSE, READ.ONLY = NULL, LOCAL = FALSE, ADD = FALSE) {}
maxima.options = set_top(...) 
```

before the real use of the generator function. See an example here:

https://github.com/jokergoo/circlize/blob/4519ae648cf7a48b26746f3ad0c7055502120489/R/global.R#L88-L92

So the first line is for generating the documentations, and from the second line is the real option function.
